### ISSUE TITLE
Is this based on the new document format?

### ISSUE THREAD

**Issue by lightsprint09** [alexjg/automerge-rs#7]
I follow along the automerge project quite I while. I am still waiting for a stable documen format. I looks like the work on the [performance](https://github.com/automerge/automerge/tree/performance) branch is related to this new format. Are you implementing already the new format in rust or still the old one.

Nevertheless great idea of brining automerge to rust. I am looking forward to use it in an iOS App.

**Comment by alexjg** [comment]
Right now we're implementing the old format. I need to update the README a bit but we're making good progress on building a WASM module which can be used by the current javascript implementation. 

Once the performance work is stabilised we'll build a rust implementation of that as well.

**Comment by lightsprint09** [comment]
Sound great.
